VectorInstitute/fed-rag

.gitignore, README.md, examples/quick-start/README.md, examples/quick-start/pyproject.toml
Finally came around to test this :) sorry for the delay.
The tool is really sleek in general, nice and easy to set up and run, and the decorator idea makes the code super clean and straightforward.
Here are a couple of small changes to the dependencies I encountered while running it for the first time.
=> Small fixes to problems I found while running the quick start example

CHANGELOG.md, pyproject.toml, uv.lock
=> [post-version] v0.0.6.post1

.github/workflows/docs.yml, docs/references.md, mkdocs.yml, pyproject.toml, src/fed_rag/utils/data/finetuning_datasets/pytorch.py, uv.lock
This PR initiates our docs, which uses mkdocs-material
=> Docs initial setup

pyproject.toml, uv.lock
Bump version to publish doc urls in PyPi
=> [version] bump version to v0.1.6.post2

examples/ra-dit/ra_dit/datasets.py, examples/ra-dit/ra_dit/main.py, examples/ra-dit/ra_dit/trainers_and_testers/generator.py, examples/ra-dit/uv.lock
https://huggingface.co/datasets/nerdai/fedrag-commonsense-qa/viewer/default/train?row=0&views%5B%5D=train
=> Example: `RA-DIT` — establish part of rig for finetuning generator on `nerdai/fedrag-commonsense-qa` dataset

examples/ra-dit/ra_dit/benchmarker.py, examples/ra-dit/ra_dit/evaluate.py, examples/ra-dit/ra_dit/evaluation_benchmarks/__init__.py, examples/ra-dit/ra_dit/evaluation_benchmarks/base.py, examples/ra-dit/ra_dit/evaluation_benchmarks/mmlu.py
This needs to be improved via:
- streaming of examples for large benchmarks
- multiprocessing
=> Example - `RA-DIT` add benchmarker module -- test on MMLU

examples/ra-dit/ra_dit/_dataset_prep/qa/math.py, examples/ra-dit/ra_dit/_dataset_prep/qa/web_questions.py, examples/ra-dit/ra_dit/_dataset_prep/qa/wiki.py
Adding three datasets.
1. web question
2. math question
3. wiki question
Closes #144
Closes #145
Closes #146
=> Example: `RA-DIT` Onboarding MathQA, WebQuestionsQA and WikiQA for fine-tuning datasets

pyproject.toml, uv.lock
Bumping to post1 to reflect README on PyPi page for fed-rag
=> [version] bump version to v0.0.8.post1 

src/fed_rag/exceptions/__init__.py, src/fed_rag/exceptions/trainer.py, src/fed_rag/trainers/huggingface/lsr.py, src/fed_rag/trainers/huggingface/mixin.py, tests/trainers/huggingface/test_hf_lsr.py
`LSRSentenceTransformerTrainer` was missing implementation for `compute_loss`. This PR adds this.
=> [Feature] Implement `compute_loss` for `LSRSentenceTransformerTrainer`

src/fed_rag/exceptions/__init__.py, src/fed_rag/exceptions/trainer.py, src/fed_rag/trainers/huggingface/lsr.py, src/fed_rag/utils/data/data_collators/huggingface.py, tests/trainers/huggingface/test_hf_lsr.py, tests/utils/data/data_collators/test_hf_data_collators.py
This PR add's `target_template` to `DataCollatorForLSR` and also makes sure that we use this in a `LSRSentenceTransformerTrainer`.
=> [Feature] Add target template to `DataCollatorForLSR`

src/fed_rag/base/data_collator.py, tests/data_collators/conftest.py, tests/data_collators/test_base.py
We need to follow similar structure for data collators as we do for trainers, trainer managers, etc. This PR handles this.
=> [Feature] Add `fed_rag.base.data_collators` and `BaseDataCollator`

docs/api_reference/data_collators/index.md, docs/api_reference/trainer_managers/index.md, docs/api_reference/trainers/huggingface.md, docs/api_reference/trainers/index.md, mkdocs.yml
Add's trainers and data collators to docs.
=> [chore] Add trainers and data collators to docs

docs/api_reference/trainers/huggingface.md, src/fed_rag/trainers/huggingface/lsr.py, tests/trainers/huggingface/test_hf_lsr.py
Rename `HuggingFaceLSRTrainer` to `HuggingFaceTrainerForLSR` to follow new convention that was adopted for RALT trainer: `HuggingFaceTrainerForRALT`.
In future, we'd make sure to alias this old name to handle backwards compatibility. But since we haven't released yet, I'm going to forego taking such measures.
=> [chore] Rename HFTrainer for LSR

docs/api_reference/trainers/huggingface.md, docs/api_reference/trainers/pytorch.md, mkdocs.yml
Just adding missing core classes to our docs.
=> [chore] Update docs with `HuggingFaceTrainerForRALT` and torch trainer classes.

src/fed_rag/data_collators/huggingface/lsr.py, src/fed_rag/data_collators/huggingface/ralt.py, src/fed_rag/trainers/huggingface/ralt.py, tests/data_collators/huggingface/test_data_collator_for_ralt.py, tests/trainers/huggingface/test_hf_ralt.py
=> [Fix] Various fixes to make RALT training work

README.md, docs/getting_started/essentials.md, docs/getting_started/quick_starts/index.md, docs/getting_started/quick_starts/rag_finetuning.md, docs/getting_started/quick_starts/rag_inference.md, docs/index.md, mkdocs.yml
This PR adds the following items to our docs:
1.  Add new quick start for fine-tuning a RAG system
2. Update the headline and philosophy to make centralized more prominent.
=> [docs] Update docs with a new quick start: fine-tune a RAG system

examples/ra-dit/ra_dit/federated_finetune.py, examples/ra-dit/uv.lock
Adds federated fine-tune script for our RA-DIT example
- [] Unit tests added or updated
=> Example: RA-DIT Add `federated_finetune.py`

docs/api_reference/knowledge_stores/qdrant.md, mkdocs.yml, pyproject.toml, src/fed_rag/exceptions/__init__.py, src/fed_rag/exceptions/knowledge_stores.py, src/fed_rag/knowledge_stores/qdrant/__init__.py, src/fed_rag/knowledge_stores/qdrant/sync.py, src/fed_rag/knowledge_stores/qdrant/utils.py, src/fed_rag/types/knowledge_node.py, tests/knowledge_stores/test_knowledge_node.py, tests/knowledge_stores/test_qdrant.py, uv.lock
This PR adds a (basic) integration into Qdrant by building a `QdrantKnowledgeStore` class that subclasses `BaseKnowledgeStore`.
- New knowledge store: `QdrantKnowledgeStore`
- Added extra/optional dependency group "qdrant" -- to use this knowledge store users should install fed rag via `pip install fed-rag[qdrant]`
- Add new custom exceptions for specificity in error handling
=> [Feature] Add Qdrant knowledge store (sync)

.gitignore, examples/knowledge_stores/ra-dit-ks/README.md, examples/knowledge_stores/ra-dit-ks/pyproject.toml, examples/knowledge_stores/ra-dit-ks/src/ra_dit_ks/__init__.py, examples/knowledge_stores/ra-dit-ks/src/ra_dit_ks/logger.py, examples/knowledge_stores/ra-dit-ks/src/ra_dit_ks/main.py, examples/knowledge_stores/ra-dit-ks/uv.lock, pyproject.toml
This PR adds an example package to build a `QdrantKnowledgeStore` that stores Wikipedia Eng. Dec 2021 facts (the same one used by RA-DIT authors). The next PR will look to package this in a docker image and push to Vector's org.
=> Example: RA-DIT knowledge store build with qdrant

docs/getting_started/quick_starts/rag_inference.md
=> [fix] chunk examples

src/fed_rag/knowledge_stores/qdrant/sync.py, tests/knowledge_stores/test_qdrant.py
Was not injecting params properly in Qdrant client.
=> [Fix] Better align to qdrant sdk

examples/knowledge_stores/ra-dit-ks/README.md, examples/knowledge_stores/ra-dit-ks/docker/Dockerfile, examples/knowledge_stores/ra-dit-ks/docker/README.md, examples/knowledge_stores/ra-dit-ks/docker/healthcheck.sh, examples/knowledge_stores/ra-dit-ks/docker/startup.sh, examples/knowledge_stores/ra-dit-ks/pyproject.toml, examples/knowledge_stores/ra-dit-ks/src/ra_dit_ks/main.py, examples/knowledge_stores/ra-dit-ks/uv.lock, examples/ra-dit/pyproject.toml, examples/ra-dit/ra_dit/rag_system.py, examples/ra-dit/uv.lock
Dockerizes knowledge store qdrant builds
```sh
docker pull vectorinstitute/qdrant-atlas-dec-wiki-2021:latest
docker run -d \
--name qdrant-vector-db \
--gpus all \
-p 6333:6333 \
-p 6334:6334 \
-v qdrant_data:/qdrant_storage \
-e TINY_SAMPLE=true \
vectorinstitute/qdrant-atlas-dec-wiki-2021:latest
```
then once healthy
```python
from fed_rag.retriever.knowledge_store import QdrantKnowledgeStore
from fed_rag.retrievers.huggingface.hf_sentence_transformer import (
HFSentenceTransformerRetriever,
)
retriever = HFSentenceTransformerRetriever(
query_model_name="nthakur/dragon-plus-query-encoder", …
```
=> Example: RA-DIT dockerize knowledge store build

docs/getting_started/how_to/index.md, docs/getting_started/tutorials/index.md, mkdocs.yml
Just a quick PR to update the scaffolding for some of our sections in our docs.
=> [docs] Button up docs—tutorials section and organize RA-DIT example

docs/examples/ra_dit/finetune.md, docs/examples/ra_dit/index.md, docs/examples/ra_dit/qdrant_knowledge_store_wikipedia.md, mkdocs.yml
Adds content to In-Depth Examples > RA-DIT > Build a Qdrant KS
=> [docs] In-depth example: Build a Qdrant KS

docs/examples/ra_dit/qdrant_knowledge_store_wikipedia.md
Add content for testing a healthy knowledge store.
=> [docs] In-depth Example: RA-DIT add missing content in qdrant ks

mkdocs.yml
Add discord invite link to FedRAG discord server
=> [docs] Add discord link

.gitignore, docs/examples/llamaindex/index.md
Adds example for using the LlamaIndex bridge
=> [docs] Add llamaindex bridge for inference example

docs/examples/llamaindex/index.md
=> [docs] Add part for the metadata in LlamaIndex example

src/fed_rag/generators/huggingface/mixin.py, tests/generators/test_hf_peft.py, tests/generators/test_hf_pretrained.py
- [] I’ve added an entry to the CHANGELOG.md (if applicable)
- Closes #
- Related to #
=> Fixing device issue in HF Generator Mixin

docs/getting_started/tutorials/index.md, docs/getting_started/tutorials/lsr.md, docs/getting_started/tutorials/ralt.md, docs/javascripts/mathjax.js, mkdocs.yml
Adds content in the "Getting Started" > "Tutorials" > "LSR" & "RALT" sections of docs.
=> [docs] Adding tutorials for LSR and RALT fine-tuning methods

CONTRIBUTING.md, docs/community/changelog.md, docs/community/contributing/ask_question.md, docs/community/contributing/index.md, docs/community/contributing/submit_issue.md, docs/community/contributing/submit_pr.md, docs/getting_started/index.md, docs/getting_started/integrations.md, mkdocs.yml
=> [docs] Community section + Integrations

docs/glossary.md, mkdocs.yml
Removing the glossary section, as it doesn't feel all that necessary (at least yet). Perhaps when we onboard more features for both FL and RAG fine-tuning will it make sense to add this as a quick refresher for our users.
=> [docs] Remove glossary section

docs/examples/ra_dit/benchmarking.md, docs/examples/ra_dit/federated_finetune.md, docs/examples/ra_dit/finetune.md
=> [docs] Small cleanup add coming soon to not yet existing docs

docs/examples/llamaindex/index.md, src/fed_rag/knowledge_stores/__init__.py
PR to fix few errors while dogfooding LlamaIndex Inference:
1. import of `InMemoryKnowledgeStore` is fixed.
2. `HFPreTrainedModelGenerator` -> `HFPretrainedModelGenerator`
3. Asking users to initialise the query.
- Closes #
- Related to #
=> Fix llamaindex inference

src/fed_rag/api/CHANGELOG.md, src/fed_rag/api/README.md, src/fed_rag/api/__init__.py, src/fed_rag/api/core.py, src/fed_rag/api/types.py, tests/api/test_api.py
This PR introduces a dedicate `.api` module that defines public interface for fed-rag. The intention being that this will be the trusted source from which our users will import stable classes and components.
- Created fed_rag/api/ module with core and types submodules
- Added backward compatibility layers to prevent breaking existing code
- Implemented comprehensive tests for API imports and stability
__For Users:__
- Clear guidance on which components are stable vs. implementation details
- Better-organized imports: from fed_rag.api import RAGSystem, RAGConfig
__For Contributors:__
- Freedom to …
=> [Feature] Adds new public api module for fed-rag (v0.0.1)

docs/getting_started/import_patterns.md, mkdocs.yml, src/fed_rag/api/CHANGELOG.md, src/fed_rag/api/__init__.py, src/fed_rag/api/generators.py, src/fed_rag/api/knowledge_stores.py, src/fed_rag/api/retrievers.py, src/fed_rag/api/types.py, src/fed_rag/base/bridge.py, src/fed_rag/types/__init__.py, src/fed_rag/types/bridge.py, tests/api/test_api.py, tests/test_imports.py
- Added: knowledge stores, retrievers, generators, rest of types
- Bump api version to v0.0.2
- Added an import patterns page 
=> [API version] Add knowledge stores, generators, retrievers and rest of types to public api (bump to v0.0.2)

.github/dependabot.yml
=> [chore] configure dependabot

docs/examples/ra_dit/qdrant_knowledge_store_wikipedia.md
Small typo in import statement for `QdrantKnowledgeStore` in the second code block.
=> [docs] Small typo in qdrant example .md

pyproject.toml, src/fed_rag/evals/__init__.py, src/fed_rag/evals/metrics/__init__.py, src/fed_rag/evals/metrics/exact_match.py, tests/evals/metrics/test_exact_match.py
Adds the first evaluation metric, namely Exact Match.
=> [Feature] Add `ExactMatchEvaluationMetric`

docs/api_reference/data_structures/bridge.md, docs/api_reference/data_structures/evals.md, docs/api_reference/data_structures/knowledge_node.md, docs/api_reference/data_structures/rag.md, docs/api_reference/data_structures/results.md, docs/api_reference/evals/benchmarker.md, docs/api_reference/evals/benchmarks/huggingface/mmlu.md, docs/api_reference/evals/index.md, docs/api_reference/evals/metrics/exact_match.md, docs/api_reference/exceptions/bridge.md, docs/api_reference/exceptions/evals.md, mkdocs.yml, src/fed_rag/data_structures/rag.py, src/fed_rag/data_structures/results.py, src/fed_rag/evals/benchmarks/huggingface/mixin.py, src/fed_rag/exceptions/__init__.py, src/fed_rag/exceptions/bridge.py, src/fed_rag/exceptions/evals.py, tests/evals/benchmarks/huggingface/test_mixin.py
Add Evals error and updates docs to include `Evals` and `Data Structures` and some missing `Exceptions`.
=> Add `EvalsError` and docs update

src/fed_rag/evals/benchmarker.py
`total_num_examples` is 0 when streaming, which is because the `Benchmark.examples` is empty when streaming.
=> [fix] fix num_total_examples in `Benchmarker`

docs/notebooks/rag_benchmarking_hf_mmlu.ipynb, src/fed_rag/base/evals/benchmark.py, src/fed_rag/evals/benchmarks/huggingface/mixin.py, tests/evals/benchmarks/_benchmarks.py, tests/evals/benchmarks/huggingface/conftest.py, tests/evals/benchmarks/huggingface/test_mixin.py, tests/evals/benchmarks/huggingface/test_mmlu.py, tests/evals/benchmarks/test_base.py
Since we handle streaming and non-streaming way to get examples from a `BenchMark`, we add a `num_examples` property to get number of examples in the benchmark.
=> [fix] Add `num_examples` abstract property to `BaseBenchmark`

docs/getting_started/quick_starts/benchmark_mmlu.md, docs/getting_started/quick_starts/index.md, docs/notebooks/rag_benchmarking_hf_mmlu.ipynb, mkdocs.yml, src/fed_rag/evals/benchmarker.py
=> [docs] Notebook and quick start guide for running benchmarks

docs/notebooks/rag_benchmarking_hf_mmlu.ipynb, mkdocs.yml
Simply forgot to add the notebook entry to our docs.
=> [chore] Add example benchmarking nb to docs

docs/notebooks/integrations/qdrant.ipynb
Just setting default `WITH_DOCKER` to true.
=> [chore] Set `WITH_DOCKER` to True in qdrant cookbook

docs/notebooks/integrations/qdrant.ipynb, src/fed_rag/data_structures/knowledge_node.py, src/fed_rag/knowledge_stores/qdrant/sync.py, tests/knowledge_stores/test_qdrant.py
…g in payload
- Closes #
- Related to #
=> Make knowledge node embedding optional and remove redundant embedding in Qdrant upserts

docs/getting_started/quick_starts/index.md
=> [chore] fix link for quick starts benchmarking RAG

pyproject.toml, src/fed_rag/generators/__init__.py, src/fed_rag/generators/unsloth/__init__.py, src/fed_rag/generators/unsloth/mixin.py, src/fed_rag/generators/unsloth/unsloth_fast_model.py, src/fed_rag/generators/unsloth/utils.py, src/fed_rag/tokenizers/unsloth_pretrained_tokenizer.py, tests/generators/test_unsloth_fast_model.py, tests/generators/test_unsloth_utils.py, tests/tokenizers/test_unsloth_pretrained.py, uv.lock
Adds a new generators integration, namely: Unsloth.
=> [Feature] Add `UnslothFastModelGenerator` 🦥 

docs/api_reference/generators/unsloth.md, mkdocs.yml, src/fed_rag/exceptions/__init__.py, src/fed_rag/exceptions/generator.py, src/fed_rag/generators/unsloth/unsloth_fast_model.py, tests/generators/test_unsloth_fast_model.py
This PR makes it possible to use peft integration with Unsloth.
=> [Feature] Support `get_peft_model` in `UnslothFastModelGenerator`

docs/notebooks/integrations/unsloth.ipynb
Uncomment installation commands in unsloth cookbook
=> [chore] docs uncomment installation instructions in unsloth cookbook

src/fed_rag/generators/huggingface/hf_peft_model.py, src/fed_rag/generators/huggingface/hf_pretrained_model.py
Refactors HFPeftModelGenerator and HFPretrainedModelGenerator to remove duplicated prompt templates, simplify optional arg handling (use `x or y` instead of ternary expressions), and clean up code for clarity and conciseness.
- Closes #
- Related to #
=> [Refactor] Simplify HF generator implementations

docs/notebooks/rag_benchmarking_hf_mmlu.ipynb, src/fed_rag/data_structures/__init__.py, src/fed_rag/data_structures/evals.py, src/fed_rag/evals/benchmarker.py, src/fed_rag/evals/utils.py, src/fed_rag/exceptions/__init__.py, src/fed_rag/exceptions/evals.py, tests/data_structures/test_evals.py, tests/evals/benchmarks/test_benchmarker.py, tests/evals/benchmarks/test_utils.py
Allows the user to save evaluated benchmark examples to disk. Also includes a utility loader for JSONL files of these evaluated examples.
Updated the notebook demonstrating how to use this feature.
=> [Feature] Add ability to save benchmark evaluations to a JSONL file

CHANGELOG.md, src/fed_rag/base/knowledge_store.py, tests/knowledge_stores/test_base.py
Mirrored the synchronous interface, but provided a default implementation for the `load_nodes` function so implementors don’t have to rewrite batch logic unless they have a more efficient bulk API.
- Closes #262 
- Related to #
=> [Feature] Add BaseAsyncKnowledgeBase (#262)

CHANGELOG.md, src/fed_rag/base/no_encode_knowledge_store.py, tests/knowledge_stores/no_encode/test_base.py
Adds no encode types for knowledge stores.
=> [feature] Add `NoEncodeBaseKnowledgeStore` and `NoEncodeAsyncBaseKnowledgeStore`

CHANGELOG.md, src/fed_rag/_bridges/llamaindex/bridge.py, src/fed_rag/base/bridge.py, src/fed_rag/data_structures/__init__.py, src/fed_rag/data_structures/bridge.py, src/fed_rag/exceptions/__init__.py, src/fed_rag/exceptions/bridge.py, src/fed_rag/exceptions/common.py, tests/bridges/test_base.py, tests/bridges/test_llamaindex.py
Introduces the TypedDict `CompatibleVersions` as described in #323, and uses it to validate the requirements of bridge framework packages.
- Closes #323 
- Related to #
=> [Feature] Verify bridge  framework version

CHANGELOG.md, src/fed_rag/knowledge_stores/no_encode/mcp/sources/base.py, src/fed_rag/knowledge_stores/no_encode/mcp/sources/stdio.py, src/fed_rag/knowledge_stores/no_encode/mcp/sources/streamable_http.py, src/fed_rag/knowledge_stores/no_encode/mcp/sources/utils.py, src/fed_rag/knowledge_stores/no_encode/mcp/store.py, tests/knowledge_stores/no_encode/mcp/test_mcp_source_stdio.py, tests/knowledge_stores/no_encode/mcp/test_mcp_source_streamable_http.py, tests/knowledge_stores/no_encode/mcp/test_mcp_store.py
- Add `rerank_callback` to `MCPKnowledgeStore`
- retrieve methods in source now return the raw `~mcp.CallToolResult`
- converter functions from `~mcp.CallToolResult` to list[KnowledgeNode] instead of a single one for more flexibility to handle the content lists and future chunking considerations.
=> [feature] Add `rerank_callback` to `MCPKnowledgeStore`

docs/notebooks/no_encode_rag_with_mcp.ipynb, mkdocs.yml
=> [docs] New cookbook for an `AsyncNoEncodeRAGSystem` using `MCPKnowledgeStore`

CHANGELOG.md, docs/notebooks/no_encode_rag_with_mcp.ipynb, src/fed_rag/base/knowledge_store.py, src/fed_rag/base/no_encode_knowledge_store.py, src/fed_rag/base/trainer.py, src/fed_rag/core/no_encode_rag_system/asynchronous.py, src/fed_rag/core/rag_system/asynchronous.py, src/fed_rag/data_collators/huggingface/ralt.py, src/fed_rag/trainers/huggingface/ralt.py, src/fed_rag/utils/asyncio.py, src/fed_rag/utils/huggingface.py, tests/knowledge_stores/no_encode/test_base.py, tests/knowledge_stores/test_base.py, tests/rag_system/test_async_no_encode_rag_system.py, tests/rag_system/test_async_rag_system.py, tests/utils/test_asyncio.py
…ata collators
This PR makes it possible to convert `AsyncRAGSystem` and `BaseAsyncKnowledgeStore` to `RAGSystem` and `BaseKnowledgeStore`, respectively. We also add the same `to_sync()` methods to no encode versions.
This PR adds a llama-index inspired `asyncio_run` utils for detecting if an event loop already exists and spinning up a new thread to handle the coro execution there.
=> [Feature] Add `to_sync()` methods for `AsyncKnowledgeStore` and `AsyncRAGSystem` and their NoEncode variants.

src/fed_rag/base/generator.py, src/fed_rag/generators/huggingface/mixin.py, tests/bridges/conftest.py, tests/conftest.py, tests/data_collators/conftest.py, tests/data_collators/huggingface/conftest.py, tests/generators/conftest.py, tests/generators/test_base.py, tests/rag_system/conftest.py, tests/trainer_managers/conftest.py, tests/trainers/conftest.py
Add a `complete()` method for generators.
=> [Feature] add complete method to `BaseGenerator`

CHANGELOG.md, pyproject.toml, src/fed_rag/utils/notebook.py
Add a utility for notebooks to be able to monitor server/client processes within a notebook.
=> [Feature] Add notebook utils process monitor

CHANGELOG.md, src/fed_rag/utils/notebook.py
Don't loop through all keys in the monitor live
=> [fix] `ProcessMonitor.monitor_live` to not loop through keys

docs/notebooks/no_encode_rag_with_mcp.ipynb
Fine-tune 0.5B Qwen2.5 generator
=> [docs] Update mcp cookbook with training of smaller generator model to avoid OOM

CHANGELOG.md, docs/api_reference/knowledge_stores/qdrant.md, docs/notebooks/integrations/qdrant_async.ipynb, src/fed_rag/knowledge_stores/qdrant/__init__.py, src/fed_rag/knowledge_stores/qdrant/asynchronous.py, src/fed_rag/knowledge_stores/qdrant/sync.py, src/fed_rag/knowledge_stores/qdrant/utils.py, tests/knowledge_stores/test_qdrant.py, tests/knowledge_stores/test_qdrant_async.py
Adds `AsyncQdrantKnowledgeStore`
=> [Feature] Add  `AsyncQdrantKnowledgeStore` and cookbook for using it within an `AsyncRAGSystem`

CHANGELOG.md, src/fed_rag/base/knowledge_store.py, src/fed_rag/base/no_encode_knowledge_store.py, src/fed_rag/knowledge_stores/in_memory.py, src/fed_rag/knowledge_stores/no_encode/mcp/store.py, src/fed_rag/knowledge_stores/qdrant/asynchronous.py, src/fed_rag/knowledge_stores/qdrant/sync.py, tests/bridges/conftest.py, tests/knowledge_stores/no_encode/mcp/test_mcp_store.py, tests/knowledge_stores/no_encode/test_base.py, tests/knowledge_stores/test_base.py, tests/knowledge_stores/test_in_memory.py, tests/knowledge_stores/test_in_memory_managed.py, tests/knowledge_stores/test_qdrant.py, tests/knowledge_stores/test_qdrant_async.py, tests/rag_system/conftest.py, tests/rag_system/test_async_no_encode_rag_system.py, tests/rag_system/test_no_encode_rag_system.py, uv.lock
- Add `batch_retrieve` abstract method to knowledge store classes
- Raise `NotImplementedError` for all existing knowledge stores
=> [Feature] Add `batch_retrieve` to knowledge store classes

CHANGELOG.md, docs/notebooks/integrations/qdrant.ipynb, docs/notebooks/integrations/qdrant_async.ipynb, src/fed_rag/knowledge_stores/qdrant/asynchronous.py, src/fed_rag/knowledge_stores/qdrant/sync.py, tests/knowledge_stores/test_qdrant.py, tests/knowledge_stores/test_qdrant_async.py
Implement batch_retrieve for `QdrantKnowledgeStore` and `AsyncQdrantKnowledgeStore`
=> [Feature] Implement `batch_retrieve` for Qdrant knowledge stores

docs/notebooks/integrations/qdrant_async.ipynb, mkdocs.yml
=> [chore] Add to qdrant async cookbook to docs

docs/notebooks/basic_fl.ipynb
=> [docs] add FL poster to cookbook

src/fed_rag/base/trainer.py
=> [chore] google style docstrings base/trainer

src/fed_rag/base/trainer_manager.py
=> [chore] docstrings for `fed_rag.base.trainer_manager`

src/fed_rag/base/trainer_config.py, tests/trainer_configs/test_pytorch_trainer_config.py
=> [chore] trainer config docstrings and fix typo in `__get_attr__`

src/fed_rag/base/tokenizer.py
=> [chore] Add docstrings for `fed_rag.base.tokenizer`

src/fed_rag/base/retriever.py, src/fed_rag/base/tokenizer.py
=> [chore] docstrings for retriever

src/fed_rag/base/no_encode_knowledge_store.py
=> [chore] docstrings for `base.no_encode_knowledge_store`

src/fed_rag/base/knowledge_store.py, src/fed_rag/base/no_encode_knowledge_store.py
=> [chore] docstrings for `BaseKnowledgeStore`.

CHANGELOG.md, src/fed_rag/base/retriever_mixins.py, src/fed_rag/base/retriever_mixins/__init__.py, src/fed_rag/base/retriever_mixins/image.py, tests/retrievers/mixins/test_image_retriever_mixin.py, uv.lock
This PR is the start of our efforts to introduce multi-modal retrieval capabilities. Specifically,
- Adds `ImageRetrieverMixin` and associated `HasImageModality` protocol for runtime/static type checking.
=> [Feature] Add base abstractions for multi-modal retriever capabilities

CHANGELOG.md, src/fed_rag/core/rag_system/_asynchronous.py, src/fed_rag/core/rag_system/_synchronous.py, tests/rag_system/test_async_rag_system.py, tests/rag_system/test_rag_system.py
In #487, we expanded the retriever encode return types, but didn't adjust the RAGSystem methods which are affected by this change. This PR, addresses them.
=> [Fix] Update `RAGSystem.retrieve` and batch version

src/fed_rag/base/data_collator.py
This pull request adds detailed docstrings in the `src/fed_rag/base/data_collator.py` module, improving code documentation and clarity for future maintainers and users. The new docstrings describe the purpose, arguments, return values, and exceptions for each class and method, making it easier to understand and use these components.
- Closes #456 
- Related to #
=> added docstrings in google style in fed_rag.base.data_collator

src/fed_rag/base/bridge.py
This pull request improves the documentation for bridge-related classes and methods in `src/fed_rag/base/bridge.py`, making the codebase easier to understand and maintain. The main focus is on enhancing docstrings to clarify the purpose, usage, and expected behavior of mixins and methods involved in bridge registration, metadata management, and compatibility checks.
Documentation improvements:
* Expanded the class-level docstring for `BridgeRegistryMixin` to explain its role in managing bridge metadata and automatic registration of bridges.
* Improved the docstring for `BaseBridgeMixin` to describe its purpose as a foundation for bridges to external frameworks, including versioning and compatibility.
Method documentation enhancements:
* Added detailed docstrings to `get_bridge_metadata` …
=> added docstrings in google style in fed_rag.base.bridge
